language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - "npm install -g codecov"
  - "npm install"
script:
  - "npm run lints"
  - "npm run lintj"
  - "npm run test"
after_script:
  - "codecov"
notifications:
  email: false
branches:
  only: 
    - master
    - develop
